### ISSUE TITLE
JavaScript error popup: Uncaught Exception: TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by rafaeltuelho** [podman-desktop/podman-desktop#3803] opened 2023-09-06 15:53 UTC
### Bug description

From time to time I see this popup suddenly appearing on my Mac...

<img width="257" alt="image" src="https://github.com/containers/podman-desktop/assets/39063/dce05f55-4aaf-4411-b01f-c6a7e2a0c96a">

The full error message is:
```
Uncaught Exception:
TypeError: Cannot read properties of null (reading 'toString')
at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:273:4914
at doneCallOnce (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/watch.js:72:17)
at LineStream.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/watch.js:83:34)
at LineStream.emit (node:events:513:28)
at emitCloseNT (node:internal/streams/destroy:132:10)
at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

### Operating system

MacOS Monterey 12.6.8 (Intel)

### Installation Method

Brew (macOS)

### Version

1.3.1

### Steps to reproduce

This pop-up appears out of nowhere from time to time while running podman-desktop.

### Additional context

MacOS Monterey (Intel)
podman 4.6.1
podman-desktop 1.3.1

**Comment by benoitf** [comment] 2023-09-06 16:05
thanks @rafaeltuelho for the report, we'll investigate. Such error should not be thrown

**Comment by lstocchi** [comment] 2023-09-06 16:10
@benoitf it looks to me a duplicate of https://github.com/containers/podman-desktop/issues/3754 that you fixed on monday

**Comment by benoitf** [comment] 2023-09-06 16:13
@lstocchi yes it looks like the same stack trace

@rafaeltuelho if you use a 'nightly' build it should be already fixed

**Comment by benoitf** [comment] 2023-09-06 16:13
1.4.0 is planned for the next week

**Comment by benoitf** [comment] 2023-09-06 16:14
Closing as a duplicate of https://github.com/containers/podman-desktop/issues/3754

**Closed as not planned by benoitf** 2023-09-06 16:14 UTC
Labels: status/need-triage
