### ISSUE TITLE
On Windows 10, the existing Kind cluster does not appear on the *Resources* page.

### ISSUE THREAD

**Issue by themr0c** [podman-desktop/podman-desktop#2405] opened 2023-05-09 14:03 UTC
### Bug description

On Windows 10, the existing Kind cluster does not appear on the *Resources* page.

### Operating system

Windows 10 Professional

### Version

next (development version)

### Steps to reproduce

1. Verify rootful mode is default: `podman system connection list`
2. *Resources > Kind > Create new* 
3. Verify Kind cluster is available for CLI: `kind get clusters`
4. You can deploy a pod to the Kind cluster and watch logs.
5. *Resources > Kind* does not show any running cluster.

(NOTE: does not happen on Linux running `yarn watch`).

### Additional context

![Screenshot from 2023-05-09 13-27-48](https://github.com/containers/podman-desktop/assets/243761/845b8aed-c150-4f07-b5c3-3899b9679599)

**Comment by odockal** [comment] 2023-05-09 14:58
Duplicate of #2080.

**Comment by nichjones1** [comment] 2023-05-17 12:15
Closed as it is a duplicate of 2080

**Closed as completed by nichjones1** 2023-05-17 12:15 UTC
Labels: area/extension/kind 🍾
